# Generated by Django 3.2.8 on 2023-11-03 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата_создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата_последнего_обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('type', models.CharField(choices=[('PR', 'Product'), ('SR', 'Service')], default='PR', max_length=300)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_shop', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата_создания')),
                ('status', models.CharField(choices=[('CM', 'Completed'), ('PN', 'Pending'), ('RJ', 'Rejected')], default='RJ', max_length=300)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shop', to='shop.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.PositiveIntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата_добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
