# Generated by Django 3.2.8 on 2023-11-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CL', 'Client'), ('MS', 'Master'), ('OW', 'Owner')], default='CL', max_length=100),
        ),
    ]
