# Generated by Django 3.2.8 on 2023-11-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Participant', 'participant'), ('Organizer', 'organizer')], default='Participant', max_length=64),
        ),
    ]
